# version: '3.8'
networks:
  kafka-net:
    driver: bridge
    
services:
  kafka:
    #image: wurstmeister/kafka  
    #image: bitnami/kafka:latest
    image: apache/kafka:latest
    #image: apache/kafka:4.1.1
    #image: apache/kafka-native:4.1.1
    #build:
     # context: .
      
#      context: .
#      dockerfile_inline: |
#        FROM alpine:latest
#        RUN apk add --no-cache nano    
    container_name: broker
#    extra_hosts:
#      - "host.docker.internal:host-gateway"    
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/var/lib/kafka/data
    environment:
      # KRaft settings
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: controller,broker
      #KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      #KAFKA_LISTENERS: PLAINTEXT://localhost:9092,CONTROLLER://localhost:9093
      #KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://localhost:9093
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      #KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT://localhost:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      #KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 3      
      # Log directory formatting (required for KRaft persistent storage)
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true #Wurstmeister Image Enables automatic topic creation The default value is "true" 
      #KAFKA_CREATE_TOPICS: "yaruss-input:1:1,yaruss-output:1:1" #Wurstmeister Image
      #KAFKA_CLUSTER_ID: $(opt/kafka/bin/kafka-storage.sh random-uuid)
      #KAFKA_CLUSTER_ID: "5L6g3nShT-eMCtK--X86sw"
    healthcheck:
      test: ["CMD", "/opt/kafka/bin/kafka-broker-api-versions.sh", "--bootstrap-server", "kafka:9092"]
      #test: ["CMD", "/opt/kafka/bin/kafka-topics.sh", "--bootstrap-server=kafka:9092", "--list"]
      #test: nc -z kafka 9092 || exit -1      
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s        
    # Use 'command' to generate a cluster UUID and format storage on first run
#    command: 
#      - "sh"
#      - "-c"
#      - "KAFKA_CLUSTER_ID=$(opt/kafka/bin/kafka-storage.sh random-uuid) && opt/kafka/bin/kafka-storage.sh format --ignore-formatted -t $$KAFKA_CLUSTER_ID -c /etc/kafka/docker/server.properties && /etc/kafka/docker/run"

    networks:
      - kafka-net
  
  init-kafka:
    #image: apache/kafka:4.1.1  
    image: apache/kafka:latest
    #image: apache/kafka-native:4.1.1    
    networks:
      - kafka-net    
    depends_on:
      kafka:
        condition: service_healthy
        #condition: service_started      
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
     "
     # Wait for Kafka to be ready
     /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --list
 
     #echo '======================== Creating kafka topics'
     /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic yaruss-input --replication-factor 3 --partitions 1
     /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic yaruss-output --replication-factor 3 --partitions 1
 
     echo '======================== Successfully created the following topics:'
     /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --list
     "
 
  app:
    container_name: spring_boot_app  
    build: .
    ports:
      - "8080:8080"
    depends_on:
      init-kafka:
      #kafka:
        #condition: service_healthy
        condition: service_started      
    #environment:
     # SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
     # SPRING_PROFILES_ACTIVE: prod
    networks:
      - kafka-net

volumes:
  kafka_data:
    driver: local
    

