#version: '3.8'

networks:
  kafka-net:
    driver: bridge
    
services:
  kafka:
    image: bitnamilegacy/kafka
    container_name: broker
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/var/lib/kafka/data
    environment:
      #- KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://kafka:9092,CONTROLLER://localhost:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      #- KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      #- KAFKA_CLUSTER_ID=QYxMVixSSZSZRJLzHL6GNQ
      #- KAFKA_BROKER_ID=1
      #- ALLOW_PLAINTEXT_LISTENER=yes
    #healthcheck:
     # test: ["CMD", "kafka-topics.sh", "--bootstrap-server=localhost:9092", "--list"]
      #start_period: 15s
      
      # Log directory formatting (required for KRaft persistent storage)
      #- KAFKA_CFG_LOG_DIRS: /var/lib/kafka/data
      #KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false' #Wurstmeister Image Enables automatic topic creation The default value is "true" 
      #KAFKA_CREATE_TOPICS: "yaruss-input:1:1,yaruss-output:1:1" #Wurstmeister Image
      #KAFKA_CLUSTER_ID: $(opt/kafka/bin/kafka-storage.sh random-uuid)
      #KAFKA_CLUSTER_ID: "5L6g3nShT-eMCtK--X86sw"
    # Use 'command' to generate a cluster UUID and format storage on first run
#    command: 
#      - "sh"
#      - "-c"
#      - "KAFKA_CLUSTER_ID=$(opt/kafka/bin/kafka-storage.sh random-uuid) && opt/kafka/bin/kafka-storage.sh format --ignore-formatted -t $$KAFKA_CLUSTER_ID -c /etc/kafka/docker/server.properties && /etc/kafka/docker/run"

    networks:
      - kafka-net

  init-kafka:
    image: bitnamilegacy/kafka
    depends_on:
      - kafka
    entrypoint: [ '/bin/sh', '-c' ]
    command:
      "
      # sleep 15
      # Wait for Kafka to be ready
      /opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --list

      echo 'Creating kafka topics'
      /opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic yaruss-input --replication-factor 3 --partitions 1
      /opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic yaruss-output --replication-factor 3 --partitions 1

      echo 'Successfully created the following topics:'
      /opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --list
      "



volumes:
  kafka_data:
    driver: local
    

