# version: '3.8'
networks:
  kafka-net:
    driver: bridge
    
services:
  kafka:
#    image: apache/kafka-native:4.1.1
#    image: bitnami/kafka:latest
    image: apache/kafka:4.1.1
    container_name: broker
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/var/lib/kafka/data
    environment:
      # KRaft settings
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: controller,broker
      #KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      #KAFKA_LISTENERS: PLAINTEXT://localhost:9092,CONTROLLER://localhost:9093
      #KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://localhost:9093
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      #KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT://localhost:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      #KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3      
      # Log directory formatting (required for KRaft persistent storage)
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      #KAFKA_CLUSTER_ID: $(opt/kafka/bin/kafka-storage.sh random-uuid)
      #KAFKA_CLUSTER_ID: "5L6g3nShT-eMCtK--X86sw"
    # Use 'command' to generate a cluster UUID and format storage on first run
#    command: 
#      - "sh"
#      - "-c"
#      - "KAFKA_CLUSTER_ID=$(opt/kafka/bin/kafka-storage.sh random-uuid) && opt/kafka/bin/kafka-storage.sh format --ignore-formatted -t $$KAFKA_CLUSTER_ID -c /etc/kafka/docker/server.properties && /etc/kafka/docker/run"

    networks:
      - kafka-net

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    environment:
      #SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - kafka-net

volumes:
  kafka_data:
    driver: local
    

